# Generated by Django 3.1.3 on 2020-11-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('classification', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('review', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, editable=False, max_length=100, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
