# Generated by Django 3.1.3 on 2020-11-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classification',
            table='classify',
        ),
    ]
